version: "3.3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379"
    networks: 
      - backend
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3309:3309'
    expose:
      - '3306'
    networks: 
      - backend
    volumes:
      - 'mysql:/var/lib/mysql/data'
  rails:
    depends_on:
      - 'mysql'
      - 'redis'
      # - 'elasticsearch'
    build: ./rails/.
    ports:
      - '3000:3000'
    networks: 
      - backend
    volumes:
      - './rails:/app'

  sidekiq:
    build: ./rails/.
    volumes:
      - './rails:/app'
    links:
      - mysql
      - redis
    command: bundle exec sidekiq
    networks: 
      - backend
    depends_on:
      - mysql
  go:
    depends_on:
      - 'redis'
    build: ./go/.
    ports:
      - '3001:3001'
    networks: 
      - backend 
    volumes:
      - './go:/app'
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
  #   ports:
  #     - "9200:9200"
  #   networks:
  #     - backend  
networks:
  backend:

volumes:
  redis:
  mysql:     
  esdata01:
    driver: local
