version: "3.3"
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks: 
      - backend
  db:
    image: mysql:5.7
    ports:
      - "7364:3306"
    networks: 
      - backend  
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
  rails:
    depends_on:
      - db
      - redis
      - elasticsearch
    build: ./rails/.
    ports:
      - 3000:3000
    networks: 
      - backend
    volumes:
      - ./rails:/app  
    environment:
      REDIS_CONNECTION_STRING: redis://redis:6379/0
      DATABASE_URL: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      ELASTICSEARCH_URL: elasticsearch:9200

  sidekiq:
    build: ./rails/.
    volumes:
      - './rails:/app'
    command: bundle exec sidekiq
    networks: 
      - backend
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      REDIS_CONNECTION_STRING: redis://redis:6379/0
      DATABASE_URL: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password

  go:
    depends_on:
      - redis
    build: ./go/.
    ports:
      - 3001:3001
    networks: 
      - backend 
    volumes:
      - ./go:/app
    environment:
      REDIS_CONNECTION_STRING: redis:6379
      HTTP_SERVER_PORT: 3001  
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend


networks:
  backend:

volumes:
  redis:
  esdata01:
    driver: local
